# Generated by Django 4.0.7 on 2022-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reqMsg', models.TextField()),
            ],
        ),
    ]
