# Generated by Django 4.0.7 on 2022-08-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0002_requestsong'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestSong',
            new_name='Request',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='reqMsg',
            new_name='request',
        ),
    ]
