# Generated by Django 4.0.7 on 2022-09-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0003_rename_requestsong_request_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='User_Report',
        ),
        migrations.RenameField(
            model_name='user_report',
            old_name='request',
            new_name='report',
        ),
    ]
