# Generated by Django 4.0.7 on 2022-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0004_rename_request_user_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
