# Generated by Django 4.0.7 on 2022-09-10 19:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0006_alter_post_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lyric',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
