# Generated by Django 4.0.7 on 2022-09-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0007_alter_post_lyric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lyric',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post_text',
            name='text',
            field=models.TextField(),
        ),
    ]
