# Generated by Django 4.0.7 on 2022-09-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0018_alter_post_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='released',
            field=models.DateTimeField(null=True),
        ),
    ]
