# Generated by Django 4.0.7 on 2022-09-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0019_alter_post_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='released',
        ),
    ]
