# Generated by Django 4.0.7 on 2022-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0021_post_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='released',
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('chinese', 'CH'), ('english', 'ENG'), ('khmer', 'KM'), ('thai', 'TH')], max_length=50),
        ),
    ]
