# Generated by Django 4.0.7 on 2022-09-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0022_remove_post_released_alter_post_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-img.jpg', null=True, upload_to='images/'),
        ),
    ]
