# Generated by Django 4.0.7 on 2022-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0023_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-img.jpg', upload_to='images/'),
        ),
    ]
